### ISSUE TITLE
Small Caps not working due to wrong classes

### ISSUE THREAD

**Issue by StudioTriple** [huertatipografica/Alegreya-libre#5]
The smcp feature replace the @smcp class by the @smcp2 class, but they only contain: 
`abreve acircumflex adieresis aring dotlessi eng eth germandbls ij thorn dotlessj kgreenlandic`

The @smcp class should be something like: 
`ae aacute abreve acircumflex adieresis agrave amacron aogonek aring atilde b c cacute ccaron ccedilla cdotaccent d dcaron e eacute ecaron ecircumflex edieresis edotaccent egrave emacron eng eogonek eth f g gbreve gcommaaccent gdotaccent h hbar i ij j iacute icircumflex idieresis igrave imacron iogonek k kcommaaccent l lacute lcaron lcommaaccent lslash m n nacute ncaron ncommaaccent ntilde o oe oacute ocircumflex odieresis ograve ohungarumlaut omacron oslash otilde p q r racute rcaron rcommaaccent s sacute scaron scedilla scommaaccent t tbar tcaron uni0162 thorn u uacute ucircumflex udieresis ugrave uhungarumlaut umacron uogonek uring v w wacute wcircumflex wdieresis wgrave x y yacute ycircumflex ydieresis ygrave z zacute zcaron zdotaccent a aringacute aeacute ccircumflex ebreve scircumflex ubreve hcircumflex itilde ibreve jcircumflex obreve oslashacute gcircumflex utilde dcroat`

And the @smcp2:
`AE.sc Aacute.sc abreve.sc acircumflex.sc adieresis.sc Agrave.sc Amacron.sc Aogonek.sc aring.sc Atilde.sc B.sc C.sc Cacute.sc Ccaron.sc Ccedilla.sc Cdotaccent.sc D.sc Dcaron.sc E.sc Eacute.sc Ecaron.sc Ecircumflex.sc Edieresis.sc Edotaccent.sc Egrave.sc Emacron.sc eng.sc Eogonek.sc eth.sc F.sc G.sc Gbreve.sc Gcommaaccent.sc Gdotaccent.sc H.sc Hbar.sc I.sc ij.sc J.sc Iacute.sc Icircumflex.sc Idieresis.sc Igrave.sc Imacron.sc Iogonek.sc K.sc Kcommaaccent.sc L.sc Lacute.sc Lcaron.sc Lcommaaccent.sc Lslash.sc M.sc N.sc Nacute.sc Ncaron.sc Ncommaaccent.sc Ntilde.sc O.sc OE.sc Oacute.sc Ocircumflex.sc Odieresis.sc Ograve.sc Ohungarumlaut.sc Omacron.sc Oslash.sc Otilde.sc P.sc Q.sc R.sc Racute.sc Rcaron.sc Rcommaaccent.sc S.sc Sacute.sc Scaron.sc Scedilla.sc Scommaaccent.sc T.sc Tbar.sc Tcaron.sc thorn.sc U.sc Uacute.sc Ucircumflex.sc Udieresis.sc Ugrave.sc Uhungarumlaut.sc Umacron.sc Uogonek.sc Uring.sc V.sc W.sc Wacute.sc Wcircumflex.sc Wdieresis.sc Wgrave.sc X.sc Y.sc Yacute.sc Ycircumflex.sc Ydieresis.sc Ygrave.sc Z.sc Zacute.sc Zcaron.sc Zdotaccent.sc A.sc Aringacute.sc AEacute.sc Ccircumflex.sc Ebreve.sc Scircumflex.sc uni021A.sc Ubreve.sc Hcircumflex.sc Itilde.sc Ibreve.sc Jcircumflex.sc Obreve.sc Oslashacute.sc Gcircumflex.sc Utilde.sc Dcroat.sc`

**Comment by juandelperal** [comment]
Hi @StudioTriple 
Sorry for the delay answering this.
The master branch is an old version. You can get the newest here: https://github.com/huertatipografica/Alegreya-libre/tree/dev

Best

**Comment by StudioTriple** [comment]
What delay? 2 days is not a delay, don't worry. Thanks for your answer!
